on:
  push:
    tags:
      - 'v*'

name: Create draft release

jobs:
  build:
    name: Create draft release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.0.0
      - name: Create draft release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release...
          draft: true
          prerelease: false